### ISSUE TITLE
Получил по ебалу от негров, но код так выдает ошибку

### ISSUE THREAD

**Issue by mbs0ft** [cyanidle/ebobot#1]
будет обновление?

**Comment by mbs0ft** [comment]
> Ты кто? _Vine boom sound effect_

ученик РАНХиГС :trollface:

**Comment by cyanidle** [comment]
Где ты негров нашел? *The Rock Stare*

**Comment by mbs0ft** [comment]
> Где ты негров нашел?

![image](https://user-images.githubusercontent.com/22106304/154481448-d3aafae5-05e8-4bc9-8e25-54cd6366f443.png)

ёмое ёлки иголки.........................

**Comment by cyanidle** [comment]
Да я делаю все методы статическими и каждый раз пишу имя класса, и что?? :100:
